server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        # Booking Service endpoints (ВСЕ endpoints через JWT фильтр)
        - id: booking-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/user/register, /api/user/auth, /api/bookings/**, /api/booking/**, /api/user/**, /api/users/**
          filters:
            - name: JwtAuthFilter
#            - RewritePath=/api/(?<segment>.*), /$\{segment}

        # Hotel Service endpoints
        - id: hotel-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/hotels/**, /api/rooms/**
          filters:
            - name: JwtAuthFilter
#            - RewritePath=/api/(?<segment>.*), /$\{segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: mySuperSecretKeyForHotelBookingSystem2024ThatIsLongEnoughForJWT!

logging:
  level:
    com.hotel.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG